---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      callback-return:
        enabled: false
    exclude_fingerprints:
      - 43ed3237cd64064f9d75f3d31466d10d
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths: []
